Develop
Hiroshi-takazoe/todolist pull request #3
Opened 2020-07-24 11:24 UTC by Hiroshi-takazoe

マージするタイミング間違えてしまい、よく分からなくなってしまいました。。。

2020-07-25 07:36 UTC, kouki-iwahara commented on challenge2/script.js
> +    let statusButton = document.createElement("input");
displayTodosの処理が膨らんでいますので、状態ボタンと削除ボタンはそれぞれ関数を定義して、処理を切り出すと良いでしょう。
状態ボタンでいうと、createStateBtnのような関数を作成し、生成したボタンをreturnで返却するイメージです。

2020-07-25 07:36 UTC, kouki-iwahara commented on challenge2/script.js
> +  if (status[0].checked) {
ラジオボタンが「すべて」の時のみしかtodoが表示されませんが意図的でしょうか？

2020-07-25 07:36 UTC, kouki-iwahara commented on challenge2/script.js
> +  let comment = document.getElementById("comment").value;
const で定義できます。
他の箇所も同様です。
再代入される場合のみletを使用しましょう^^

2020-07-25 07:36 UTC, kouki-iwahara commented on challenge2/script.js
> +addButton.addEventListener("click", function() {
`"click"`となっていますが、文字列は`''`で囲みましょう。

2020-07-26 13:09 UTC, Hiroshi-takazoe commented on challenge2/script.js
> +  if (status[0].checked) {
ご察しの通り、意図的に入れています。
後ほど条件分岐の際に使用すると判断しましたので、予め挿入してしまいました。。。

2020-07-27 12:06 UTC, kouki-iwahara commented on challenge2/script.js
> +    cell3.appendChild(createStateBtn());
createStateBtn()でreturnされた要素は一度変数に格納しましょう。
予期せぬバグを生んでしまうのと、後にクリックイベントを付与することとなります。
削除ボタンも同様です。

2020-07-28 11:20 UTC, myzktkyk requested changes
やや細かい指摘をいたしました。ご確認ください。

2020-07-28 11:20 UTC, myzktkyk commented on challenge2/script.js
> +    let newIdNumber = document.createTextNode(idNumber);
変数 `newIdNumber` がこれ以降で使われていないようです。
不要であれば削除しましょう。

2020-07-28 11:20 UTC, myzktkyk commented on challenge2/script.js
> +  };
`;` は不要なので削除しておきましょう。

2020-07-29 11:11 UTC, Dok1211 commented on challenge2/script.js
> +function displayTodos() {
functionはアロー関数に置き換えてみてください
参考
https://qiita.com/may88seiji/items/4a49c7c78b55d75d693b

2020-07-29 11:11 UTC, Dok1211 commented on challenge2/script.js
> +  const comment = document.getElementById('comment').value;
今の実装だとinputが空の場合でもtodoが追加されてしまうので、
空の場合は追加しないようにしてみましょう

2020-07-29 11:11 UTC, Dok1211 commented on challenge2/script.js
> +  for (var i = 0; i < todos.length; i++) {
varはletに置き換えましょう

2020-07-29 11:11 UTC, Dok1211 commented on challenge2/script.js
> +    const idNumber = document.createTextNode(todos.length - 1);
createTextNode()の引数はstring(文字列)なので
todos.length - 1を文字列に置き換えましょう

2020-07-29 11:11 UTC, Dok1211 commented on challenge2/script.js
> +    tdNumber[i].textContent = idNumber;
textContentに代入する値はstring(文字列)がふさわしいので
idNumberを文字列に置き換えましょう

2020-07-31 14:35 UTC, merged